#=
--- Day 7: Laboratories ---
You thank the cephalopods for the help and exit the trash compactor, finding yourself in the familiar halls of a North Pole research wing.

Based on the large sign that says "teleporter hub", they seem to be researching teleportation; you can't help but try it for yourself and step onto the large yellow teleporter pad.

Suddenly, you find yourself in an unfamiliar room! The room has no doors; the only way out is the teleporter. Unfortunately, the teleporter seems to be leaking magic smoke.

Since this is a teleporter lab, there are lots of spare parts, manuals, and diagnostic equipment lying around. After connecting one of the diagnostic tools, it helpfully displays error code 0H-N0, which apparently means that there's an issue with one of the tachyon manifolds.

You quickly locate a diagram of the tachyon manifold (your puzzle input). A tachyon beam enters the manifold at the location marked S; tachyon beams always move downward. Tachyon beams pass freely through empty space (.). However, if a tachyon beam encounters a splitter (^), the beam is stopped; instead, a new tachyon beam continues from the immediate left and from the immediate right of the splitter.

For example:

.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
In this example, the incoming tachyon beam (|) extends downward from S until it reaches the first splitter:

.......S.......
.......|.......
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At that point, the original beam stops, and two new beams are emitted from the splitter:

.......S.......
.......|.......
......|^|......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
Those beams continue downward until they reach more splitters:

.......S.......
.......|.......
......|^|......
......|.|......
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
At this point, the two splitters create a total of only three tachyon beams, since they are both dumping tachyons into the same place between them:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
This process continues until all of the tachyon beams reach a splitter or exit the manifold:

.......S.......
.......|.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.|.|.|.|||.|
To repair the teleporter, you first need to understand the beam-splitting properties of the tachyon manifold. In this example, a tachyon beam is split a total of 21 times.

Analyze your manifold diagram. How many times will the beam be split?
=#


function main(lines)
    str_sub(S,str,n1,n2) = @. SubString(S,1,n1-1) * str * SubString(S,n2+1,length(S))

    result = 0
    file_length = length(lines)
    file_width = length(lines[1])
    println("length: $(file_length)")
    println("width: $(file_width)")
    bin_tree = zeros(((file_length ÷ 2) - 1, file_width))

    # Convert to binary tree
    kdx = 0
    for idx in collect(3:2:file_length-1)
        kdx+=1
        for jdx in collect(1:file_width)
            if (lines[idx-2][jdx] == 'S' || lines[idx-2][jdx] == '|') && lines[idx][jdx] == '^'
                result += 1
                lines[idx] = str_sub(lines[idx], "|", jdx-1, jdx-1)
                lines[idx] = str_sub(lines[idx], "|", jdx+1, jdx+1)
            elseif (lines[idx-2][jdx] == 'S' || lines[idx-2][jdx] == '|') && lines[idx][jdx] == '.'
                lines[idx] = str_sub(lines[idx], "|", jdx, jdx)
            end
        end
        println(lines[idx])
        # for jdx in collect(1:file_width)
        #     if lines[idx][jdx] == '^'
        #         bin_tree[kdx, jdx] = 1
        #     end
        # end
    end
    return result
    # display(bin_tree)
end

print(("="^10)*"Starting:"*("="^10)*"\n")
final_answer = 0
f = open("2025\\day07\\puzzle_input.txt", "r")
lines = readlines(f)
final_answer = main(lines)
close(f)


println("Final answer=$(final_answer)")
print(("="^10) * "DONE" * ("="^10)*"\n")